---
pagetitle: "CStories.app - Home"
listing:
  - id: list-infographics
    contents:
      - "infographics/*.qmd"
    type: grid
    categories: true
  - id: list-news
    contents:
    - "news/*.qmd"
    type: grid
    sort-ui: false
    filter-ui: false
    field-types:
      published_at: date
    fields: [title, description, published_at, source, image]
    field-display-names:
      published_at: "Published"
    sort: 
      - "published_at desc"
      - "title"
    max-items: 3
    page-size: 3
    table-striped: true
    # categories: true
format:
  html:
    include-after-body: lib/bot.html
    css:
    - "/lib/bot.css"
    - "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/4.0.2/bootstrap-material-design.css"
    - "https://fonts.googleapis.com/icon?family=Material+Icons"
---

***Empowering Communities with Easy-to-Use Digital Tools to Participate in Marine Renewable Energy Planning & Development***

## Features

Here are the core features of this Beta digital tool for empowering communities to participate in marine renewable energy planning & development.

::: {.grid}

##### {{< fa image >}} Infographics {.g-col-12 .g-col-med-6 .g-col-lg-3}
Explore interactive infographics. Click on elements in a whole system to find out more about each and see how they are related.

##### {{< fa newspaper >}} News {.g-col-12 .g-col-med-6 .g-col-lg-3}
News sources across the internet and specific to wind energy areas in California get scraped to find the latest news in offshore wind.

##### {{< fa robot >}} Ask AI {.g-col-12 .g-col-med-6 .g-col-lg-3}
We connect you to the latest Artificial Intelligence (OpenAI GPT) to get immediate answers to your questions on marine renewable energy. We log the questions and answers, so we can perform an expert review and provide human-verified answers.

##### {{< fa comment >}} Comments {.g-col-12 .g-col-med-6 .g-col-lg-3}
Use the comment system available in the upper right corner to then highlight and comment (aka "annotate") on any text from infographics to news items.

:::

::: {.callout-caution}

## This website product is under development

This website [cstories.app/**beta**](https://cstories.app/beta) is where we're organizing product features (e.g. news, infographics, AI chat bot) into a dedicated website, whereas the parent website
[cstories.app](https://cstories.app){target="_blank"} is for organizing community feedback.
:::


## Infographics

Interactive infographics allow for easy navigation of core concepts and information in a visual manner.

::: {#list-infographics}
:::

## News

Here are the three most recent news items about offshore wind. [View all news](news.qmd)

::: {#list-news}
:::

## Contact

-   Grace Chang ([gchang\@integral-corp.com](gchang@integral-corp.com); 831-576-2881)

-   Ben Best ([ben\@ecoquants.com](mailto:ben@ecoquants.com); 805-705-9770)


<script type="text/javascript">
document.getElementById("list-news-pagination").style.visibility = "hidden";
</script>
