---
pagetitle: "Whales"
---

{{< video https://youtu.be/G8bKpuSNUZ0 >}}

Adapted from the [Tethys](https://tethys.pnnl.gov/publications/humpback-whales-floating-offshore-wind-farm-animation){target="_blank"} site: Commercial interest in developing floating wind energy in the deep waters of the Pacific Outer Continental Shelf has raised questions about whales and other large cetaceans potentially encountering the mooring lines and electrical cables from a floating offshore wind farm. Pacific Northwest National Laboratory created an animated simulation of a humpback whale mother and her calf swimming through a hypothetical floating offshore wind farm to visualize the scale of the whales compared to the scale of the wind farm’s underwater components. This simulation helps characterize the risk of whale encounters with mooring lines and electrical cables. The floating wind farm shown in the video is a hypothetical but realistic depiction of what could be installed off the U.S. west coast and Hawaii. Humpbacks were chosen as the whale species to depict because of their presence in the Pacific Region and their large pectoral fins—appendages that could make them more likely to encounter the mooring lines and electrical cables if they are swimming nearby.

Source: [Exploring Encounters between Humpback and Floating Wind Farms | PNNL](https://www.pnnl.gov/news-media/exploring-encounters-between-humpback-and-floating-wind-farms){target="_blank"}
